/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as GameRouteRouteImport } from './routes/game/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as GameGameIdRouteImport } from './routes/game/$gameId'
import { Route as appNewGameRouteImport } from './routes/(app)/new-game'
import { Route as appJoinGameIdRouteImport } from './routes/(app)/join.$gameId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRouteRoute = GameRouteRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => GameRouteRoute,
} as any)
const appNewGameRoute = appNewGameRouteImport.update({
  id: '/new-game',
  path: '/new-game',
  getParentRoute: () => appRouteRoute,
} as any)
const appJoinGameIdRoute = appJoinGameIdRouteImport.update({
  id: '/join/$gameId',
  path: '/join/$gameId',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/game': typeof GameRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/new-game': typeof appNewGameRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/': typeof appIndexRoute
  '/join/$gameId': typeof appJoinGameIdRoute
}
export interface FileRoutesByTo {
  '/game': typeof GameRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/new-game': typeof appNewGameRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/': typeof appIndexRoute
  '/join/$gameId': typeof appJoinGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/game': typeof GameRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/(app)/new-game': typeof appNewGameRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/join/$gameId': typeof appJoinGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/game'
    | '/logout'
    | '/new-game'
    | '/game/$gameId'
    | '/'
    | '/join/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/game'
    | '/logout'
    | '/new-game'
    | '/game/$gameId'
    | '/'
    | '/join/$gameId'
  id:
    | '__root__'
    | '/(app)'
    | '/game'
    | '/logout'
    | '/(app)/new-game'
    | '/game/$gameId'
    | '/(app)/'
    | '/(app)/join/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  GameRouteRoute: typeof GameRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/(app)/new-game': {
      id: '/(app)/new-game'
      path: '/new-game'
      fullPath: '/new-game'
      preLoaderRoute: typeof appNewGameRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/join/$gameId': {
      id: '/(app)/join/$gameId'
      path: '/join/$gameId'
      fullPath: '/join/$gameId'
      preLoaderRoute: typeof appJoinGameIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appNewGameRoute: typeof appNewGameRoute
  appIndexRoute: typeof appIndexRoute
  appJoinGameIdRoute: typeof appJoinGameIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appNewGameRoute: appNewGameRoute,
  appIndexRoute: appIndexRoute,
  appJoinGameIdRoute: appJoinGameIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface GameRouteRouteChildren {
  GameGameIdRoute: typeof GameGameIdRoute
}

const GameRouteRouteChildren: GameRouteRouteChildren = {
  GameGameIdRoute: GameGameIdRoute,
}

const GameRouteRouteWithChildren = GameRouteRoute._addFileChildren(
  GameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  GameRouteRoute: GameRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
