# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge develop
on:
  push:
    branches:
      - develop
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Verify Changed files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        id: changed-files
        with:
          files: |
            .nvmrc
            src/
            package.json
            pnpm-lock.yaml
            eslint.config.js
            firebase.json
            tsconfig
            vite.config.ts
            vitest.config.ts
  build_and_deploy:
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.should_run == 'true' }}
    needs: check-changes
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: |
          echo "${{ secrets.DEV_CLIENT_ENV }}" > .env
      - run: pnpm build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NPRD_SCRUM_POKER }}
          channelId: live
          projectId: nprd-scrum-poker
