name: 'Code Review by Gemini AI'

on:
  pull_request:
    types:
      - labeled

jobs:
  review:
    if: ${{ github.event.label.name == 'Code Review' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: 'Get diff of the pull request'
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: '${{ github.event.pull_request.head.ref }}'
          PULL_REQUEST_BASE_REF: '${{ github.event.pull_request.base.ref }}'
        run: |-
          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}"
          git fetch origin "${{ env.PULL_REQUEST_BASE_REF }}"
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
          git diff "origin/${{ env.PULL_REQUEST_BASE_REF }}" > "diff.txt"
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT
      - uses: rubensflinco/gemini-code-review-action@1.0.5
        name: 'Code Review by Gemini AI'
        id: review
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: 'gemini-2.5-flash-lite'
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}
          pull_request_chunk_size: '3500'
          extra_prompt: |-
            You are a senior software engineer. You are asked to provide a code review with 
            helpful suggestions for the following pull request.
            Make sure you only focus on the code referenced in the diff.
            Be concise and focus on the most impactful suggestions only.
          log_level: 'DEBUG'
