name: 'Code Review by Gemini AI'

on:
  pull_request:
    types:
      - labeled

jobs:
  review:
    if: ${{ github.event.label.name == 'Code Review' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: 'Get diff of the pull request'
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: '${{ github.event.pull_request.head.ref }}'
          PULL_REQUEST_BASE_REF: '${{ github.event.pull_request.base.ref }}'
        run: |-
          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}"
          git fetch origin "${{ env.PULL_REQUEST_BASE_REF }}"
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
          git diff "origin/${{ env.PULL_REQUEST_BASE_REF }}" > "diff.txt"
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT
      - uses: rubensflinco/gemini-code-review-action@1.0.5
        name: 'Code Review by Gemini AI'
        id: review
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: 'gemini-2.5-flash'
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}
          pull_request_chunk_size: '3500'
          extra_prompt: |-
            You are a senior software engineer and a security expert. Your task is to review the provided code diff for a pull request.
            Focus on identifying potential bugs, security vulnerabilities, performance issues, and areas for code improvement.
            Provide concise, actionable feedback with specific code examples where applicable.
            Prioritize critical issues such as security flaws and major bugs.
            Adhere to best practices in software engineering and security.
            Only comment on the code within the diff.
            Be polite and constructive in your suggestions.
          log_level: 'DEBUG'
      - name: 'Remove "Code Review" label'
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Code Review

      - name: 'Add "Reviewed" label'
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Reviewed
